services:
  django:
    container_name: toodaloo
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    container_name: postgres
    image: postgres:15.2
    environment:
      - POSTGRES_USER=toodaloo
      - POSTGRES_PASSWORD=toodaloo
      - POSTGRES_DB=toodaloo
    ports:
      - "10016:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.0.11
    ports:
      - 6379:6379
volumes:
  postgres_data:
